import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainFooter from "@/components/layout/MainFooter";
import MainHeader from "@/components/layout/MainHeader";

const inter = Inter({ subsets: ['latin'], variable: '--inter' })
export const metadata: Metadata = {
  title: "Roooby - NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="grid grid-cols-12 gap-8 mx-[9.25rem]">
        <MainHeader />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
